/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_flexdock_docking_drag_outline_win32_Win32RubberBand */

#ifndef _Included_org_flexdock_docking_drag_outline_win32_Win32RubberBand
#define _Included_org_flexdock_docking_drag_outline_win32_Win32RubberBand
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SINGLETON */
/*
 * Class:     org_flexdock_docking_drag_outline_win32_Win32RubberBand
 * Method:    drawRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_flexdock_docking_drag_outline_win32_Win32RubberBand_drawRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_flexdock_docking_drag_outline_win32_Win32RubberBand
 * Method:    clearRectangle
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_flexdock_docking_drag_outline_win32_Win32RubberBand_clearRectangle
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_flexdock_docking_drag_outline_win32_Win32RubberBand
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_flexdock_docking_drag_outline_win32_Win32RubberBand_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
